name: Run Python Script Hourly

on:
  schedule:
    - cron: '5 * * * *'  # Run at 5 minutes past every hour
  workflow_dispatch:      # Enable manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory
        run: pwd

      - name: List files before running
        run: ls -al

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies for pyodbc
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas sqlalchemy pyodbc

      - name: Run Python script and capture all output
        run: |
          echo "Starting script execution..."
          python ItemStatus.py > log.txt 2>&1 || echo "Script failed (non-zero exit)"
          echo "Script finished."

      - name: List files after running
        run: ls -al

      - name: Show contents of log.txt if it exists
        if: always()
        run: |
          if [ -f log.txt ]; then
            echo "Log output:"
            cat log.txt
          else
            echo "log.txt not found!"
          fi

      - name: Upload log file (if created)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-log
          path: log.txt
