name: Run Python Script Weekly

on:
  schedule:
    - cron: '0 * * * *'  # Every Monday at 09:00 UTC
  workflow_dispatch:  # Optional: allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run the script
        run: python ItemStatus.py

